Feature/sql agence voyage
JJeanniard/CDA_2005 pull request #88
Opened 2020-09-30 12:01 UTC by JJeanniard

A regardé

2020-10-01 06:52 UTC, mdevoldere requested changes
Pour la vue n°3 , la partie "TR.trip_code + order_quantity nbr_strip" renvoie un résultat faux ;)

2020-10-01 07:56 UTC, JJeanniard commented
Correction de l'erreur dans le dossier step_1

2020-10-01 08:01 UTC, JJeanniard commented
Step 2 avec

2020-10-03 07:38 UTC, mdevoldere approved these changes

2020-10-04 08:12 UTC, merged